### ISSUE TITLE
is there something newer? or why so inactive?

### ISSUE THREAD

**Issue by mnewmedia** [nkashyap/console.io#38]
is there something newer? or why so inactive?

**Comment by nkashyap** [comment]
do you have any features in mind?

**Comment by mnewmedia** [comment]
nope not at the moment. Just don't wanted to go with a repo, without the maintainer carying any longer.. But you are still here so that's all i wanted =) PS: Thanks for sharing!

**Comment by nkashyap** [comment]
Yes, if you find any bug then do let me know, I'll fix is asap.
