### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by Mangor** [nkashyap/console.io#39]
There is an error when run "consoleio" command:

```
Starting Console.IO
module.js:341
    throw err;
    ^

Error: Cannot find module './node_modules/coffee-script'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by nkashyap** [comment]
Just tried it inside vagrant box with node version 5. for some reason when installed as global express.io and express where not installed properly.

To fix this issue, please execute following command:

change current working directory to:

/xconsole.io/node_modules/express.io
npm install

/xconsole.io/node_modules/express
npm install

please try above and let me know if it works for your.

**Comment by Mangor** [comment]
Thanks! Works fine for me.
