### ISSUE TITLE
No device connecting

### ISSUE THREAD

**Issue by itamayo** [nkashyap/console.io#41]
Hi !

First of all thanks for this great tool. I have used so many times, and it worked perfect.
But, after some months without used, I try to install it last week but I have several problems with the installation using NPM, it throws some errors with some paths, like it could not found a correct path of express and could install it dependencies. I have try with different node version but I have same problem.

Anyway, that is no my biggest problem, I have resolved those problem by executing npm manually on the correspond paths. So, I can execute consoleio and seem that runs fine, I can see the debug web page and my web site with the inyected script of consoleio it seems that works fine, since it connects with the WS and send something, but it no get connected. Always shows the same status:

> ...Registration|offline|websocket

I will appreciate any comment or any help =)

**Comment by nkashyap** [comment]
so it works in web browser but not in device?

**Comment by itamayo** [comment]
Thanks for so quick response =)

It is no working for me as should be. The debugger app it no showing any device and the the device that should be been debugging is not pass the state of "registration". I did some test changing this lines:

https://github.com/nkashyap/console.io/blob/master/server/manager.js#L134

It get connected and the debugger apps show the device in the list but I can't debug it because it said that there is not devices when I do doubleClick on the list of the device...

**Comment by itamayo** [comment]
I don't know what is going wrong, buut something related with the serialNumber, I had to hard code a random serial number as cookie it is working now. Thanks anyway.
